apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - name: http
      port: {{ .Values.service.portHttp }}
      targetPort: 80
    - name: https
      port: {{ .Values.service.portHttps }}
      targetPort: 443
    - name: ssh
      port: {{ .Values.service.portSsh }}
      targetPort: 22
  type: {{ .Values.service.type }}
